### ISSUE TITLE
LAPACK_ROW_MAJOR error!

### ISSUE THREAD

**Issue by getengqing** [Macbull/ELM-Caffe#2]
When I added the LSLayer, I got the error:
Error: 'LAPACK_ROW_MAJOR' 、LAPACKE_dgelsd and so on ,has not been declared in this scope!
How I solver it?Thanks!

**Comment by Macbull** [comment]
Hi @getengqing, Extremely sorry for late reply. 
My first guess is that Intel MKL library is not installed. This implementation of LSLayer needs Intel MKL library. Can you confirm ?

**Comment by getengqing** [comment]
Thanks, I used the openblas library!
